name: AnImprovedMarketplace
favicon: null
layout_spectrum: 0.9096131543628871
typography_spectrum: 0.3656276010442525
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0069aa'
    - '#f9ddb5'
    - '#ee4423'
    - '#f288b8'
    - '#549b01'
  brandStrength: 0.1519537502899766
  lightness: 0.629882620414719
  saturation: 0.6121805489528924
  rhythmicContrast: 0.3097631437703967
purpose: []
